site_name: Documentação - IHC - Codeforces

nav:
    - Home: index.md
    - Guia De Estilo:
        - 1. Introdução: guia_de_estilo/1.introducao.md
        - 2. Resultados De Análise: guia_de_estilo/2.resultados_analise.md
        - 3. Elementos De Interface: guia_de_estilo/3.elementos_interface.md
        - 4. Elementos De Interação: guia_de_estilo/4.elementos_interacao.md
        - 5. Elementos De Ação: guia_de_estilo/5.elementos_de_acao.md
        - 6. Vocabularios E Padrões: guia_de_estilo/6.vocabularios_e_padroes.md
    - Artefatos:
        - StoryBoard: artefatos/storyboard.md
    - Contexto de uso:
        - Análise de usuário: contexto_de_uso/analise_de_usuario.md
        - Análise de tarefas: contexto_de_uso/analise_de_tarefas.md
        - Características da plataforma: contexto_de_uso/caracteristicas_plataforma.md
        - Princípios gerais de projeto: contexto_de_uso/principios_gerais.md
    - Concepção/Avaliação:
        - Protótipo de papel: concepcao/prototipo_de_papel.md
        - Planejamento da avaliação: concepcao/planejamento_avaliacao.md
    - Avaliação:
        - Heurística:
            - Resultados 1: avaliacao/heuristica/erick_fernando.md
            - Resultados 2: avaliacao/heuristica/bruno_eugenio.md
            - Resultados 3: avaliacao/heuristica/geise_lorrany.md
            - Relato final: avaliacao/heuristica/relato_final.md
repo_url: https://github.com/IHC-2019-2/2019.2-CodeForces

docs_dir: codeforces_docs/
site_dir: docs/

theme: yeti
