site_name: IHC - Codeforces

nav:
    - Guia De Estilo:
        - 1. Introdução: guia_de_estilo/1.introducao.md
        - 2. Resultados De Análise: guia_de_estilo/2.resultados_analise.md
        - 3. Elementos De Interface: guia_de_estilo/3.elementos_interface.md
        - 4. Elementos De Interação: guia_de_estilo/4.elementos_interacao.md
        - 5. Elementos De Ação: guia_de_estilo/5.elementos_de_acao.md
        - 6. Vocabularios E Padrões: guia_de_estilo/6.vocabularios_e_padroes.md
    - Contexto de uso:
        - Análise de usuário: contexto_de_uso/analise_de_usuario.md
        - Análise de tarefas: contexto_de_uso/analise_de_tarefas.md
        - Características da plataforma: contexto_de_uso/caracteristicas_plataforma.md
        - Princípios gerais de projeto: contexto_de_uso/principios_gerais.md
    - Concepção/Avaliação:
        - Planejamento da avaliação: concepcao/planejamento_avaliacao.md
        - StoryBoard: artefatos/storyboard.md
    - Avaliação:
        - Formativa:
            - Relato final: avaliacao/formativa/relato-final.md
        - Heurística:
            - Resultados Erick_Fernando: avaliacao/heuristica/erick_fernando.md
            - Resultados Bruno_Eugênio: avaliacao/heuristica/bruno_eugenio.md
            - Resultados Geise_Lorrany: avaliacao/heuristica/geise_lorrany.md
            - Relato final: avaliacao/heuristica/relato_final.md
        - Percurso Cognitivo:
            - Resultados 1: avaliacao/percurso_cognitivo/erick_fernando.md
            - Resultados 2: avaliacao/percurso_cognitivo/bruno_eugenio.md
            - Resultados 3: avaliacao/percurso_cognitivo/geise_lorrany.md
            - Relato Final: avaliacao/percurso_cognitivo/relato_final_cognitivo.md
        - Contexto De Uso:
            - Avaliação Contexto de Uso: avaliacao/contexto_de_uso/avaliacao_contexto_de_uso.md
            - Avaliação Alexandre: avaliacao/contexto_de_uso/avaliacao_alexandre.md
    - Acessibilidade:
        - Padrão W3C: acessibilidade/w3c.md
        - Padrão eMAG: acessibilidade/emag.md
        - Google lighthouse: acessibilidade/codeforces_lighthouse.md
        - Consolidação dos resultados: acessibilidade/consolidacao_dos_resultados.md
    - Prototipacao:
        - Alta Fidelidade: prototipacao/alta_fidelidade.md
        - Protótipo de papel: concepcao/prototipo_de_papel.md

repo_url: https://github.com/IHC-2019-2/2019.2-CodeForces

docs_dir: codeforces_docs/
site_dir: docs/

theme: yeti
